name: Docker Build for Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build and test with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag card-service:$(date +%s)

    - name: Push Docker image
      run: docker push your-docker-image-name
